# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: strapper 0.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "strapper"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kyle Daigle"]
  s.date = "2014-10-10"
  s.description = "Strapper is a tool to help you make sure your environment is ready to run your project. It uses things like Homebrew to install the required tools but is softer than Boxen or Vagrant to manage what you need."
  s.email = "kyle@digitalworkbox.com"
  s.executables = ["strapper"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "bin/strapper",
    "lib/strapper.rb",
    "lib/strapper/brew.rb",
    "lib/strapper/cmd.rb",
    "lib/strapper/parser.rb",
    "lib/strapper/recipe.rb",
    "lib/strapper/recipes/homebrew.rb",
    "lib/strapper/recipes/pow.rb",
    "lib/strapper/registry.rb",
    "lib/strapper/version.rb",
    "strapper.gemspec",
    "test/helper.rb",
    "test/test_strapper.rb"
  ]
  s.homepage = "http://github.com/kdaigle/strapper"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A simple tool to help you manage dependencies and other 'bootstrap' tasks for your project."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<commander>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<commander>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<commander>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

